version: '3'
services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456*"
      MYSQL_DATABASE: "shop"
      MYSQL_USER: "api"
      MYSQL_PASSWORD: "123456*"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysql_data: