server:
  port: ${SERVER_PORT:5000}
spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/shop?allowMultiQueries=true}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:api}
    password: ${MYSQL_PASSWORD:123456*}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${DDL_AUTO:none}
  liquibase:
    enabled: true
  mail:
    admin: ${MAIL_ADMIN:your-email@example.com}
    active: ${MAIL_ACTIVE:false}
    host: smtp.example.com
    port: 587
    username: ${MAIL_USERNAME:your-email@example.com}
    password: ${MAIL_PASS:your-email-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

seeder:
  run: ${SEEDER_RUN:false}